import { collection, doc, setDoc, getDoc, getDocs, query, where } from 'firebase/firestore'
import { db } from '../firebase'

// Generate daily report data
export async function generateDailyReport(date = new Date()) {
  const dateStr = date.toISOString().split('T')[0]
  const [adsSnap, vehiclesSnap] = await Promise.all([
    getDocs(collection(db, 'ads')),
    getDocs(collection(db, 'vehicles')),
  ])
  const ads = adsSnap.docs.map(d => ({ id: d.id, ...d.data() }))
  const vehicles = vehiclesSnap.docs.map(d => ({ id: d.id, ...d.data() }))

  return {
    type: 'daily',
    date: dateStr,
    generatedAt: new Date().toISOString(),
    kpis: {
      totalAds: ads.length,
      activeAds: ads.filter(a => a.status === 'Active').length,
      totalVehicles: vehicles.length,
      activeVehicles: vehicles.filter(v => v.status === 'Active').length,
      totalImpressions: ads.reduce((s, a) => s + (a.impressions || 0), 0),
    },
    topAds: ads.filter(a => a.status === 'Active').sort((a, b) => (b.impressions || 0) - (a.impressions || 0)).slice(0, 5).map(a => ({ title: a.title, company: a.company, impressions: a.impressions || 0 })),
    vehicleSummary: {
      online: vehicles.filter(v => { if (!v.lastHeartbeat) return false; const d = v.lastHeartbeat.toDate ? v.lastHeartbeat.toDate() : new Date(v.lastHeartbeat); return (new Date() - d) / 1000 < 300 }).length,
      total: vehicles.length,
    },
  }
}

// Generate weekly report
export async function generateWeeklyReport(startDate, endDate) {
  const daily = await generateDailyReport()
  return {
    type: 'weekly',
    startDate: startDate?.toISOString?.() || new Date().toISOString(),
    endDate: endDate?.toISOString?.() || new Date().toISOString(),
    generatedAt: new Date().toISOString(),
    ...daily,
  }
}

// Generate monthly report
export async function generateMonthlyReport(month, year) {
  const daily = await generateDailyReport()
  return {
    type: 'monthly',
    month,
    year,
    generatedAt: new Date().toISOString(),
    ...daily,
  }
}

// Generate HTML for email
export function generateReportHTML(reportData) {
  const { kpis, topAds, vehicleSummary, type, date } = reportData
  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body { font-family: Arial, sans-serif; background: #f8fafc; margin: 0; padding: 20px; }
  .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
  .header { background: linear-gradient(135deg, #1e3a5f, #0f2439); color: white; padding: 24px; text-align: center; }
  .header h1 { margin: 0; font-size: 24px; }
  .header p { margin: 8px 0 0; opacity: 0.7; font-size: 14px; }
  .kpis { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; padding: 24px; }
  .kpi { background: #f1f5f9; border-radius: 12px; padding: 16px; text-align: center; }
  .kpi .value { font-size: 28px; font-weight: bold; color: #1e3a5f; }
  .kpi .label { font-size: 12px; color: #64748b; text-transform: uppercase; letter-spacing: 1px; margin-top: 4px; }
  .section { padding: 0 24px 24px; }
  .section h2 { font-size: 16px; color: #334155; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }
  .ad-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #f1f5f9; }
  .footer { background: #f1f5f9; padding: 16px 24px; text-align: center; color: #94a3b8; font-size: 12px; }
</style></head>
<body>
<div class="container">
  <div class="header">
    <h1>AdMotion Report</h1>
    <p>${type === 'daily' ? 'Daily' : type === 'weekly' ? 'Weekly' : 'Monthly'} Performance Summary - ${date || new Date().toLocaleDateString()}</p>
  </div>
  <div class="kpis">
    <div class="kpi"><div class="value">${kpis?.totalAds || 0}</div><div class="label">Total Ads</div></div>
    <div class="kpi"><div class="value">${kpis?.activeAds || 0}</div><div class="label">Active Ads</div></div>
    <div class="kpi"><div class="value">${kpis?.totalVehicles || 0}</div><div class="label">Total Vehicles</div></div>
    <div class="kpi"><div class="value">${kpis?.totalImpressions?.toLocaleString() || 0}</div><div class="label">Impressions</div></div>
  </div>
  <div class="section">
    <h2>Top Performing Ads</h2>
    ${(topAds || []).map(ad => `<div class="ad-row"><span>${ad.title}</span><span><strong>${ad.impressions?.toLocaleString()}</strong> views</span></div>`).join('')}
  </div>
  <div class="section">
    <h2>Fleet Status</h2>
    <p>${vehicleSummary?.online || 0} of ${vehicleSummary?.total || 0} vehicles currently online</p>
  </div>
  <div class="footer">
    <p>Generated by AdMotion Platform | ${new Date().toLocaleString()}</p>
  </div>
</div>
</body></html>`
}

// Save report preferences
export async function saveReportPreference(adminId, preferences) {
  await setDoc(doc(db, 'reportPreferences', adminId), {
    ...preferences,
    updatedAt: new Date().toISOString(),
  })
}

// Get report preferences
export async function getReportPreference(adminId) {
  const snap = await getDoc(doc(db, 'reportPreferences', adminId))
  return snap.exists() ? snap.data() : null
}
